plugins {
  id 'java'
  id 'org.springframework.boot' version '3.4.3'
  id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(21)
  }
}

repositories {
  mavenCentral()
}

configurations {
    compileJs {}
}

dependencies {
  compileJs('com.google.javascript:closure-compiler:v20131014')
  implementation 'org.springframework.boot:spring-boot-starter-web'
}

// jar {
//     baseName = 'alphashape'
//     version = '1.0'
// }

//war {
//    baseName = 'alphashape'
//    version =  '1.0'
//    archiveName = 'alphashape.war'
//}

def jsLibFiles = [
  'alphashape/namespace.js',
  'alphashape/util/namespace.js',
  'alphashape/geom/namespace.js',
  'alphashape/ds/namespace.js',
  'alphashape/algo/namespace.js',

  'alphashape/util/constant.js',
  'alphashape/util/comparator.js',
  'alphashape/util/array.js',

  'alphashape/geom/pathelement.js',
  'alphashape/geom/vector.js',
  'alphashape/geom/line.js',
  'alphashape/geom/linesegment.js',
  'alphashape/geom/rectangle.js',
  'alphashape/geom/arc.js',
  'alphashape/geom/circle.js',
  'alphashape/geom/triangle.js',
  'alphashape/geom/bezier.js',
  'alphashape/geom/halfplane.js',
  'alphashape/geom/polygon.js',

  'alphashape/ds/tree.js',
  'alphashape/ds/dcel.js',

  'alphashape/algo/convexhull.js',
  'alphashape/algo/skyum.js',
  'alphashape/algo/fortune.js',
  'alphashape/algo/voronoidelaunay.js',
  'alphashape/algo/alphashape.js'
]

def jsAppFiles = [
        'canvas/namespace.js',
        'application/namespace.js',
        'ui/namespace.js',

        'canvas/drawer.js',
        'canvas/canvasdrawer.js',
        'canvas/svgdrawer.js',
        'canvas/drawingcontroller.js',
        'canvas/canvaseventcontroller.js',

        'ui/filemenu.js',
        'ui/alphashapedialog.js',
        'ui/voronoidialog.js',

        'util/misc.js',

        'application/computations.js',
        'application/shareddata.js',
        'application/application.js'
]

def jsAppCanvasFiles = [
        'canvas/namespace.js',
        'application/namespace.js',

        'canvas/drawer.js',
        'canvas/canvasdrawer.js',
        'canvas/svgdrawer.js',
        'canvas/drawingcontroller.js',
        'canvas/canvaseventcontroller.js',

        'util/misc.js',

        'application/computations.js',
        'application/shareddata.js',
        'application/applicationcanvas.js'
]

task compileLib(type: JavaExec) {
    def jsRoot = 'src/main/webapp/js/'
    def jsFiles = jsLibFiles
    def jsPaths = jsFiles.collect { jsRoot + it }
    def jsOutputFile = 'src/main/webapp/js/compiled/alphashape-lib.js'
    new File('src/main/webapp/js/compiled').mkdirs()

    classpath = configurations.compileJs
    main = 'com.google.javascript.jscomp.CommandLineRunner'
    args = ['--js'] + jsPaths + ['--js_output_file', jsOutputFile,
                                 '--warning_level', 'VERBOSE',
                                 '--summary_detail_level', '3']
}

task compileApp(type: JavaExec) {
    def jsRoot = 'src/main/webapp/js/'
    def jsFiles = jsLibFiles + jsAppFiles
    def jsPaths = jsFiles.collect { jsRoot + it }
    def jsOutputFile = 'src/main/webapp/js/compiled/alphashape-app.js'
    new File('src/main/webapp/js/compiled').mkdirs()

    classpath = configurations.compileJs
    main = 'com.google.javascript.jscomp.CommandLineRunner'
    args = ['--js'] + jsPaths + ['--js_output_file', jsOutputFile,
                                 '--externs', 'src/main/webapp/js/externs.js',
                                 '--warning_level', 'VERBOSE',
                                 '--summary_detail_level', '3']
}

task compileAppCanvas(type: JavaExec) {
    def jsRoot = 'src/main/webapp/js/'
    def jsFiles = jsLibFiles + jsAppCanvasFiles
    def jsPaths = jsFiles.collect { jsRoot + it }
    def jsOutputFile = 'src/main/webapp/js/compiled/alphashape-canvas.js'
    new File('src/main/webapp/js/compiled').mkdirs()

    classpath = configurations.compileJs
    main = 'com.google.javascript.jscomp.CommandLineRunner'
    args = ['--js'] + jsPaths + ['--js_output_file', jsOutputFile,
                                 '--externs', 'src/main/webapp/js/externs.js',
                                 '--warning_level', 'VERBOSE',
                                 '--summary_detail_level', '3']
}
