function AlphaShape(){}AlphaShape.alphas;AlphaShape.calcAlphaShape=function(a,b,c){AlphaShape.alphaShape=[];AlphaShape.alphas=[];for(var d=0;d<c.length;d++){var f=-1*c[d].getMaxDist(),e=-1*c[d].getMinDist();AlphaShape.alphas.push(f);AlphaShape.alphas.push(e);0>a&&a>f&&a<e&&AlphaShape.alphaShape.push(c[d].delaunayEdge)}for(d=0;d<b.length;d++)f=b[d].getMinDist(),e=b[d].getMaxDist(),AlphaShape.alphas.push(f),AlphaShape.alphas.push(e),0<=a&&a>f&&a<e&&AlphaShape.alphaShape.push(b[d].delaunayEdge)};function Circle(a,b){this.center=a;this.radius=b};function ConvexHull(){}ConvexHull.makeRightTurn=function(a){return 0<Vector.calcDet(a[0],a[1],a[2])};ConvexHull.calcHalfConvexHull=function(a){if(1<a.length){for(var b=a.slice(0,2),c=2;c<a.length;c++)for(b.push(a[c]);2<b.length&&!ConvexHull.makeRightTurn(b.slice(-3));)b.splice(-2,1);return b}return a.slice(0)};
ConvexHull.calcConvexHull=function(a){ConvexHull.convexHull=[];a=Misc.removeDoublesFromArray(a,Vector.compareByXThenY);if(1<a.length){a.sort(Vector.compareByXThenY);var b=ConvexHull.calcHalfConvexHull(a);a.sort(function(a,b){return-1*Vector.compareByXThenY(a,b)});a=ConvexHull.calcHalfConvexHull(a);ConvexHull.convexHull=b.concat(a);ConvexHull.convexHull=Misc.removeDoublesFromArray(ConvexHull.convexHull,Vector.compareByXThenY)}else ConvexHull.convexHull=a.slice(0)};function EdgeList(){this.vertices=[];this.faces=[];this.halfEdges=[]}
EdgeList.prototype={constructor:EdgeList,getNewFace:function(){var a=new Face;this.faces.push(a);return a},getNewHalfEdge:function(){var a=new HalfEdge;this.halfEdges.push(a);return a},getNewHalfEdgePair:function(){var a=this.getNewHalfEdge(),b=this.getNewHalfEdge();a.twin=b;return b.twin=a},getNewVertex:function(){var a=new Vertex;this.vertices.push(a);return a},getFace:function(a){var b=null;this.faces.forEach(function(c){a.equals(c.vector)&&(b=c)});return b},getVertex:function(a){var b=null;this.vertices.forEach(function(c){a.equals(c.coordinates)&&
(b=c)});return b},getHalfEdge:function(a,b){var c=null;this.halfEdges.forEach(function(d){a.equals(d.origin.coordinates)&&b.equals(d.twin.origin.coordinates)?c=d:b.equals(d.origin.coordinates)&&a.equals(d.twin.origin.coordinates)&&(c=d)});return c},getLineSegments:function(){var a=[],b=[];this.halfEdges.forEach(function(c){b.some(function(a){return c===a||c.twin===a})||(a.push(c.getLineSegment()),b.push(c))});return a}};function Vertex(){this.incidentEdge=this.coordinates=null}
function Face(){this.innerComponent=this.outerComponent=this.vector=null;this.innerComponents=[]}Face.prototype={constructor:Face,getOuterBorder:function(){for(var a=[],b=this.outerComponent.getStart();null!==b;)a.push(b.getLineSegment()),b=b.next;return a}};function HalfEdge(){this.prev=this.next=this.incidentFace=this.twin=this.origin=null}
HalfEdge.prototype={constructor:HalfEdge,getStart:function(){for(var a=this;null!==a.prev&&a.prev!==this;)a=a.prev;return a},getEnd:function(){for(var a=this;null!==a.next&&a.next!==this;)a=a.next;return a},setNext:function(a){this.next=a;a.prev=this},setPrev:function(a){this.prev=a;a.next=this},getLineSegment:function(){return LineSegment.createFromPoints(this.origin.coordinates,this.twin.origin.coordinates)}};var drag={x:0,y:0,selected:!1,move:!1},points=[];function initPaper(){var a=$('<canvas id="canvas"/>');$("#draw").append(a);a=$('<canvas id="tickCanvas"/>');$("#alphaSliderTicks").append(a);$("#canvas").mousedown(handleDragStart);$("#canvas").mousemove(handleDragMove);$("#canvas").mouseup(handleDragEnd);$("#canvas").bind("touchstart",handleTouchDragStart);$("#canvas").bind("touchmove",handleTouchDragMove);$("#canvas").bind("touchend",handleTouchDragEnd)}
$(function(){$("#buttons").buttonset();$("#checkAlphaShape").attr("checked","true");$("#checkAlphaShape").button();$("#alphaSlider").slider();$("#alphaSlider").slider("option","min",-2500);$("#alphaSlider").slider("option","max",2500);$("#alphaSlider").slider("option","value",0);$("#alphaSlider").slider("option","slide",redraw);$("#alphaSlider").slider("option","change",redraw);$("#alphaSlider").slider("option","stop",redraw);$("#clearPoints").button();$("#svgLink").button();$("#pointsLink").button();
$("#checkConvexHull").change(redraw);$("#checkSmallestCircle").change(redraw);$("#checkDTc").change(redraw);$("#checkVDc").change(redraw);$("#checkDTf").change(redraw);$("#checkVDf").change(redraw);$("#checkAlphaShape").change(redraw);$("#clearPoints").click(function(){points=[];redraw()});jQuery.ajaxSetup({async:!1});jQuery.getJSON("data/points.json",function(a){for(var b=0;b<a.length;b++)points.push(new Vector(a[b].x,a[b].y))});initPaper();redraw()});window.onresize=function(){redraw()};
function handleDragStart(a){if(!drag.selected){var b=a.pageX-$("#canvas").offset().left;a=a.pageY-$("#canvas").offset().top;dragStart(b,a)}return!1}function handleTouchDragStart(a){if(!drag.selected){var b=a.originalEvent.targetTouches[0].pageX-$("#canvas").offset().left;a=a.originalEvent.targetTouches[0].pageY-$("#canvas").offset().top;dragStart(b,a)}return!1}
function dragStart(a,b){var c=Misc.getIndexOfElementWithMinimalDistance(points,new Vector(a,b),Vector.calcDist,20);drag.x=a;drag.y=b;0<=c&&(drag.selected=!0)}function handleDragMove(a){if(drag.selected){var b=a.pageX-$("#canvas").offset().left;a=a.pageY-$("#canvas").offset().top;dragMove(b,a)}}
function handleTouchDragMove(a){if(drag.selected){var b=a.originalEvent.changedTouches[0].pageX-$("#canvas").offset().left;a=a.originalEvent.changedTouches[0].pageY-$("#canvas").offset().top;dragMove(b,a)}}function dragMove(a,b){var c=new Vector(drag.x,drag.y),d=new Vector(a,b);1<c.sub(d).abs()&&(drag.move=!0);removePoint(drag.x,drag.y);addPoint(a,b);drag.x=a;drag.y=b;redraw()}function handleDragEnd(a){var b=a.pageX-$("#canvas").offset().left;a=a.pageY-$("#canvas").offset().top;dragEnd(b,a)}
function handleTouchDragEnd(a){var b=a.originalEvent.changedTouches[0].pageX-$("#canvas").offset().left;a=a.originalEvent.changedTouches[0].pageY-$("#canvas").offset().top;dragEnd(b,a)}function dragEnd(a,b){if(drag.selected)drag.move||removePoint(drag.x,drag.y);else{var c=new Vector(drag.x,drag.y),d=new Vector(a,b);5>c.sub(d).abs()&&addPoint(drag.x,drag.y)}drag.selected=!1;drag.move=!1;redraw()}function addPoint(a,b){var c=new Vector(a,b);points.push(c)}
function removePoint(a,b){var c=Misc.getIndexOfElementWithMinimalDistance(points,new Vector(a,b),Vector.calcDist,20);0<=c&&points.splice(c,1)}
function redraw(){$("#canvas")[0].width=window.innerWidth-25;$("#canvas")[0].height=window.innerHeight-180;$("#alphaSlider").width(window.innerWidth-50);$("#tickCanvas")[0].width=window.innerWidth-50;$("#tickCanvas")[0].height=10;drawPoints();ConvexHull.calcConvexHull(points);var a=$("#alphaSlider").slider("value"),b=$("#alphaSlider").slider("option","min"),c=$("#alphaSlider").slider("option","max");a===b?($("#alphaValue").html("-infinity"),a=-1*Misc.INFINITY):a===c?($("#alphaValue").html("+infinity"),
a=Misc.INFINITY):$("#alphaValue").html(a);$("#checkConvexHull").is(":checked")&&drawConvexHull(ConvexHull.convexHull,"black");1<ConvexHull.convexHull.length&&(Fortune.compute(points),Skyum.unifiedSkyum(ConvexHull.convexHull),AlphaShape.calcAlphaShape(a,Fortune.voronoiNeighbours,Skyum.voronoiNeighbours),setSliderTicks(AlphaShape.alphas),$("#checkSmallestCircle").is(":checked")&&drawSmallestCircle(Skyum.smallestCircle,"black"),$("#checkDTc").is(":checked")&&drawEdges(Fortune.delaunayTriangulation,"#00FF00"),
$("#checkVDc").is(":checked")&&drawEdges(Fortune.voronoiDiagram,"#00FFFF"),$("#checkDTf").is(":checked")&&drawEdges(Skyum.delaunayTriangulation,"#00FF00"),$("#checkVDf").is(":checked")&&drawEdges(Skyum.voronoiDiagram,"#00FFFF"),$("#checkAlphaShape").is(":checked")&&highlightEdges(AlphaShape.alphaShape,"#FF0000"));$("#svgLink").attr("href","data:image/svg;charset=utf-8,"+encodeURIComponent($("#draw").html()));$("#pointsLink").attr("href","data:application/json;charset=utf-8,"+encodeURIComponent(JSON.stringify(points)))}
function drawPoints(){var a=$("#canvas")[0];if(a.getContext)for(var a=a.getContext("2d"),b=0;b<points.length;b++)a.beginPath(),a.arc(points[b].x,Math.round(points[b].y),5,0,2*Math.PI,!1),a.fill()}function drawConvexHull(a){var b=$("#canvas")[0];if(1<a.length&&b.getContext){b=b.getContext("2d");b.beginPath();b.moveTo(a[0].x,a[0].y);for(var c=1;c<a.length;c++)b.lineTo(a[c].x,a[c].y);b.closePath();b.stroke()}}
function drawSmallestCircle(a){var b=$("#canvas")[0];if(b.getContext)for(var b=b.getContext("2d"),c=0;c<points.length;c++)b.beginPath(),b.arc(a.center.x,a.center.y,a.radius,0,2*Math.PI,!1),b.stroke()}function drawEdges(a,b){var c=$("#canvas")[0];if(c.getContext){c=c.getContext("2d");c.strokeStyle=b;for(var d=0;d<a.length;d++)c.beginPath(),c.moveTo(a[d].origin.x,a[d].origin.y),c.lineTo(a[d].getEndpoint().x,a[d].getEndpoint().y),c.stroke()}}
function highlightEdges(a,b){var c=$("#canvas")[0];if(c.getContext){c=c.getContext("2d");c.strokeStyle=b;c.globalAlpha=0.5;c.lineWidth=5;for(var d=0;d<a.length;d++)c.beginPath(),c.moveTo(a[d].origin.x,a[d].origin.y),c.lineTo(a[d].getEndpoint().x,a[d].getEndpoint().y),c.stroke()}}
function setSliderTicks(a){var b=$("#tickCanvas")[0],c=$("#alphaSlider").slider("option","min"),d=$("#alphaSlider").slider("option","max");a=a.filter(function(a){return a>c&&a<d});a.sort();for(var f=b.getContext("2d"),e=0;e<a.length;e++){var g=(a[e]-c)/(d-c)*b.width;f.beginPath();f.moveTo(g,0);f.lineTo(g,10);f.stroke()}};function FortuneTree(){this.root=null}FortuneTree.prototype=Object.create(Tree.prototype);FortuneTree.prototype.constructor=FortuneTree;FortuneTree.prototype.getArcNodeAboveEvent=function(a){if(this.isEmpty())return null;for(var b=this.root,c;!b.isLeaf();)c=b.content,c=c.getLocation(a.y),b=a.x<=c.x?b.leftChild:b.rightChild;return b};
FortuneTree.prototype.insertNewArcNode=function(a,b){var c=new Arc(a),d=b.getNewFace();d.vector=a;c.face=d;if(this.isEmpty())return this.root=new TreeNode(c),{newArcNode:this.root,arcNodeAbove:null};var f=this.getArcNodeAboveEvent(a),e=f.content,g=e.face,h=b.getNewHalfEdgePair();h.incidentFace=d;d.outerComponent=h;h.twin.incidentFace=g;null===g.outerComponent&&(g.outerComponent=h.twin);e.vector.x<=c.vector.x?(d=new Breakpoint(e,c),g=new Breakpoint(c,e)):(d=new Breakpoint(c,e),g=new Breakpoint(e,c));
d.halfEdge=h;g.halfEdge=h.twin;h=new TreeNode(e);c=new TreeNode(c);e=new TreeNode(e);g=new TreeNode(g);d=new TreeNode(d);d.setLeftChild(h);d.setRightChild(c);g.setLeftChild(d);g.setRightChild(e);this.replaceNode(f,g);return{newArcNode:c,arcNodeAbove:f}};
FortuneTree.prototype.deleteArcNode=function(a){var b,c,d,f,e,g,h;b=a.nodes[1];c=b.getLeftSibling();d=b.getRightSibling();f=b.parent;e=this.getCommonAncestor(c,d);var k=e.content.getLocation(a.v.y),l=(new Breakpoint(c.content,d.content)).getLocation(a.v.y),m=(new Breakpoint(d.content,c.content)).getLocation(a.v.y),l=k.sub(l).abs(),k=k.sub(m).abs(),k=l<=k?!1:!0;e.isInLeftSubtree(f)?(g=f,h=e):e.isInRightSubtree(f)&&(g=e,h=f);b.isLeftChild()?this.replaceNode(f,f.rightChild):this.replaceNode(f,f.leftChild);
this.updateInnerNode(e,c,d,k);b=Fortune.V.getNewVertex();b.coordinates=a.circle.center;a=g.content.halfEdge;h=h.content.halfEdge;g=Fortune.V.getNewHalfEdgePair();a.origin=b;h.origin=b;g.origin=b;b.incidentEdge=g;a.setPrev(h.twin);a.twin.setNext(g);h.setPrev(g.twin);g.incidentFace=a.twin.incidentFace;g.twin.incidentFace=h.incidentFace;e.content.halfEdge=g.twin;return{formerLeftSibling:c,formerRightSibling:d,success:!0}};
FortuneTree.prototype.updateInnerNodes=function(){this.inorderDo(function(a){if(!a.isLeaf()){var b=a.leftChild.getRightmostChild(),c=a.rightChild.getLeftmostChild().content;a.content.leftArc=b.content;a.content.rightArc=c}})};FortuneTree.prototype.updateInnerNode=function(a,b,c,d){a.isLeaf()||(b=b.content,c=c.content,d?(a.content.leftArc=c,a.content.rightArc=b):(a.content.leftArc=b,a.content.rightArc=c))};
FortuneTree.prototype.checkStructure=function(a){var b=!0;this.inorderDo(function(c){if(!c.isLeaf()){var d=c.content.getLocation(a);if(!c.leftChild.isLeaf()){var f=c.leftChild.content.getLocation(a);-1===Misc.compareWithTolerance(d.x,f.x,Misc.TOLERANCE)&&(b=!1)}c.rightChild.isLeaf()||(c=c.rightChild.content.getLocation(a),1===Misc.compareWithTolerance(d.x,c.x,Misc.TOLERANCE)&&(b=!1))}});return b};
FortuneTree.prototype.getBreakpointsString=function(a){var b="";this.inorderDo(function(c){c.isLeaf()||(b+=c.content.getLocation(a).x+" , ")});return b};function Arc(a){this.vector=a;this.face=null}Arc.prototype={getY:function(a,b){var c=this.vector.x,d=this.vector.y,c=a*a-2*c*a+c*c+d*d-b*b,f=2*(d-b);if(0!==Misc.compareWithTolerance(d,b,Misc.TOLERANCE))return c/f},toString:function(){return"("+this.vector.toString()+")"}};
function Breakpoint(a,b){this.leftArc=a;this.rightArc=b;this.halfEdge=null}
Breakpoint.prototype={isOnlyBreakpoint:function(){return this.leftArc.vector.y===this.rightArc.vector.y},isLeftBreakpoint:function(){return this.leftArc.vector.x<this.rightArc.vector.x||this.leftArc.vector.x===this.rightArc.vector.x&&this.leftArc.vector.y>this.rightArc.vector.y?!0:!1},isRightBreakpoint:function(){return this.leftArc.vector.x>this.rightArc.vector.x||this.leftArc.vector.x===this.rightArc.vector.x&&this.leftArc.vector.y<this.rightArc.vector.y?!0:!1},getLocation:function(a){var b=this.leftArc.vector.x,
c=this.leftArc.vector.y,d=this.rightArc.vector.x,f=this.rightArc.vector.y,e=f-c,g=2*(d*(c-a)-b*(f-a)),h=(f-a)*(b*b+c*c-a*a)-(c-a)*(d*d+f*f-a*a);0===Misc.compareWithTolerance(f,c,Misc.TOLERANCE)?e=(b+d)/2:(b=(-g+Math.sqrt(g*g-4*e*h))/(2*e),e=(-g-Math.sqrt(g*g-4*e*h))/(2*e),e=this.isLeftBreakpoint()?Math.min(b,e):Math.max(b,e));g=this.leftArc.getY(e,a);a=this.rightArc.getY(e,a);if(void 0!==g)return new Vector(e,g);if(void 0!==a)return new Vector(e,a)},getOrigin:function(){return this.leftArc.vector.add(this.rightArc.vector).multiplyScalar(0.5)},
getDirection:function(){if(this.isOnlyBreakpoint())return this.leftArc.vector.sub(this.rightArc.vector).rotate(Math.PI/2).normalize();var a,b;this.leftArc.vector.y>this.rightArc.vector.y?(a=this.leftArc.vector,b=this.rightArc.vector):(a=this.rightArc.vector,b=this.leftArc.vector);return this.isLeftBreakpoint()?a.sub(b).rotate(Math.PI/2).normalize():b.sub(a).rotate(Math.PI/2).normalize()},calcHalfEdgeOrigin:function(){this.halfEdge.origin=new Vertex;this.halfEdge.origin.coordinates=this.getOrigin().add(this.getDirection().multiplyScalar(Misc.INFINITY))},
toString:function(){return"<"+this.leftArc.toString()+"-"+this.rightArc.toString()+">"}};function FortuneEvent(a,b){this.v=a;this.type=b;this.nodes=[];this.circle=null}FortuneEvent.prototype={involvesNode:function(a){var b=!1;this.nodes.forEach(function(c){a===c&&(b=!0)});return b},toString:function(){return this.v+" "+this.type}};FortuneEvent.compareByYThenX=function(a,b){return Vector.compareByYThenX(a.v,b.v)};function Fortune(){}
Fortune.compute=function(a){Fortune.Q=[];Fortune.T=new FortuneTree;Fortune.V=new EdgeList;Fortune.voronoiNeighbours=[];Fortune.voronoiDiagram=[];Fortune.delaunayTriangulation=[];Fortune.voronoiNeighbours=[];a.forEach(function(a){Fortune.Q.push(new FortuneEvent(a,"site"))});for(Fortune.Q.sort(function(a,c){return-1*FortuneEvent.compareByYThenX(a,c)});0!==Fortune.Q.length;)a=Fortune.Q[0],Fortune.Q.splice(0,1),"site"===a.type?Fortune.handleSiteEvent(a):"circle"===a.type&&Fortune.handleCircleEvent(a),
Fortune.Q.sort(function(a,c){return-1*FortuneEvent.compareByYThenX(a,c)});Fortune.T.inorderDo(function(a){a.isLeaf()||null===a.content.halfEdge.origin&&a.content.calcHalfEdgeOrigin()});Fortune.evaluateEdgeList()};
Fortune.handleSiteEvent=function(a){var b=Fortune.T.insertNewArcNode(a.v,Fortune.V);a=b.newArcNode;var c=b.arcNodeAbove;a.isRoot()||(Fortune.Q=Fortune.Q.filter(function(a){return"site"===a.type?!0:a.nodes[1]!==c}),b=a.getLeftSibling(),a=a.getRightSibling(),Fortune.insertNewCircleEvents(b),Fortune.insertNewCircleEvents(a))};
Fortune.handleCircleEvent=function(a){var b=Fortune.T.deleteArcNode(a);b.success&&(Fortune.Q=Fortune.Q.filter(function(b){return"site"===b.type?!0:!b.involvesNode(a.nodes[1])}),Fortune.insertNewCircleEvents(b.formerLeftSibling),Fortune.insertNewCircleEvents(b.formerRightSibling))};Fortune.insertNewCircleEvents=function(a){var b=a.getLeftSibling(),c=a.getRightSibling();null!==b&&null!==c&&(a=Fortune.checkTripleForCircleEvent(b,a,c),null!==a&&Fortune.Q.push(a))};
Fortune.checkTripleForCircleEvent=function(a,b,c){var d=a.content.vector,f=b.content.vector,e=c.content.vector,g=null;if(0<=Vector.calcDet(d,f,e)||d===e||d===f||f===e)return null;g=new Triangle(d,f,e);d=g.getCircumcircle().center;f=g.getCircumcircle().radius;g=new Vector(d.x,d.y-f);g=new FortuneEvent(g,"circle");g.nodes.push(a);g.nodes.push(b);g.nodes.push(c);g.circle=new Circle(d,f);return g};
Fortune.evaluateEdgeList=function(){Fortune.voronoiDiagram=Fortune.V.getLineSegments();Fortune.delaunayTriangulation=VoronoiDelaunay.computeDelaunay(Fortune.V).getLineSegments();Fortune.voronoiNeighbours=VoronoiDelaunay.computeVoronoiNeighbours(Fortune.V)};function Line(a,b){this.origin=a;this.direction=b}
Line.prototype={constructor:Line,pointProjection:function(a){var b=new Vector(0,0);return this.direction.equals(b)?null:this.origin.add(this.direction.multiplyScalar(a.sub(this.origin).multiplyVector(this.direction)/this.direction.abssquare()))},calculateLambda:function(a){var b=new Vector(0,0);if(this.direction.equals(b))return this.origin.equals(a)?0:null;if(0===Misc.compareWithTolerance(this.direction.x,0))return 0!==Misc.compareWithTolerance(this.origin.x,a.x)?null:a=(a.y-this.origin.y)/this.direction.y;
if(0===Misc.compareWithTolerance(this.direction.y,0))return 0!==Misc.compareWithTolerance(this.origin.y,a.y)?null:a=(a.x-this.origin.x)/this.direction.x;b=(a.x-this.origin.x)/this.direction.x;return 0!==Misc.compareWithTolerance(b,(a.y-this.origin.y)/this.direction.y)?null:b},containsPoint:function(a){return null!==this.calculateLambda(a)?!0:!1},getIntersection:function(a){var b=this.direction.normalize().add(a.direction.normalize()),c=new Vector(0,0),d=this.direction.normalize().multiplyScalar(2);
if(a.direction.equals(c)||this.direction.equals(c))return a.origin.equals(this.origin)?a.origin:null;if(b.equals(c)||b.equals(d))return null;a=0!==Misc.compareWithTolerance(a.direction.x,0)?(a.origin.y+(this.origin.x-a.origin.x)*a.direction.y/a.direction.x-this.origin.y)/(this.direction.y-this.direction.x*a.direction.y/a.direction.x):(a.origin.x-this.origin.x)/this.direction.x;return this.origin.add(this.direction.multiplyScalar(a))}};function LineSegment(a,b){this.origin=a;this.direction=b}LineSegment.createFromPoints=function(a,b){return new LineSegment(a,b.sub(a))};
LineSegment.prototype={constructor:LineSegment,getEndpoint:function(){return this.origin.add(this.direction)},getCenter:function(){return this.origin.add(this.direction.multiplyScalar(0.5))},getLength:function(){return this.direction.abs()},pointProjection:function(a){a=(new Line(this.origin,this.direction)).pointProjection(a);return this.containsPoint(a)?a:null},containsPoint:function(a){a=(new Line(this.origin,this.direction)).calculateLambda(a);return null===a?!1:-1!==Misc.compareWithTolerance(a,
0)&&1!==Misc.compareWithTolerance(a,1)},getIntersection:function(a){var b=new Line(this.origin,this.direction),c=new Line(a.origin,a.direction),b=b.getIntersection(c);return null!==b?this.containsPoint(b)&&a.containsPoint(b)?b:null:null},equals:function(a){return this.origin.equals(a.origin)&&this.getEndpoint().equals(a.getEndpoint())||this.origin.equals(a.getEndpoint())&&this.getEndpoint().equals(a.origin)?!0:!1}};function Misc(){}Misc.TOLERANCE=1E-9;Misc.INFINITY=1E6;Misc.getIndexOfElementWithMinimalDistance=function(a,b,c,d){var f=-1,e=null;void 0===d&&(d=Misc.INFINITY);for(var g=0;g<a.length;g++){var h=Math.abs(c(b,a[g]));h<d&&(null===e?(e=h,f=g):h<e&&(e=h,f=g))}return f};Misc.getIndexInArray=function(a,b,c){for(var d=0;d<a.length;d++)if(0===c(a[d],b))return d;return-1};Misc.getIndexInArrayWithPredicate=function(a,b){for(var c=0;c<a.length;c++)if(b(a[c]))return c;return-1};
Misc.removeDoublesFromArray=function(a,b){for(var c=[],d=0;d<a.length;d++){var f=a[d];-1===Misc.getIndexInArray(c,f,b)&&c.push(f)}return c};Misc.compareArrays=function(a,b,c){if(a.length!==b.length)return!1;for(var d=0;d<a.length;d++)if(0!==c(a[d],b[d]))return!1;return!0};Misc.sign=function(a){return 0>a?-1:0===a?0:1};Misc.compareWithTolerance=function(a,b,c){void 0===c&&(c=Misc.TOLERANCE);a-=b;return Math.abs(a)<c?0:0>a?-1:1};Misc.compare=function(a,b){return a===b?0:a<b?-1:1};
Misc.doWithStopWatch=function(a,b){var c=Array.prototype.slice.call(arguments,1),d=Date.now(),c=a.apply(null,c);return{time:Date.now()-d,result:c}};function Ray(a,b){this.origin=a;this.direction=b}
Ray.prototype={constructor:Ray,pointProjection:function(a){a=(new Line(this.origin,this.direction)).pointProjection(a);return this.containsPoint(a)?a:null},containsPoint:function(a){a=(new Line(this.origin,this.direction)).calculateLambda(a);return null===a?!1:-1!==Misc.compareWithTolerance(a,0)},getIntersection:function(a){var b=new Line(this.origin,this.direction),c=new Line(a.origin,a.direction),b=b.getIntersection(c);return null!==b?this.containsPoint(b)&&a.containsPoint(b)?b:null:null}};function Rectangle(a,b,c,d){this.points=[];this.points[0]=new Vector(a,b);this.points[1]=new Vector(a,d);this.points[2]=new Vector(c,d);this.points[3]=new Vector(c,b);this.ls=[];this.ls[0]=LineSegment.createFromPoints(this.points[0],this.points[1]);this.ls[1]=LineSegment.createFromPoints(this.points[1],this.points[2]);this.ls[2]=LineSegment.createFromPoints(this.points[2],this.points[3]);this.ls[3]=LineSegment.createFromPoints(this.points[3],this.points[0])}
Rectangle.prototype={constructor:Rectangle,getIntersections:function(a){for(var b=[],c=0;4>c;c++){var d=this.ls[c].getIntersection(a);null!==d&&b.push(d)}return b=Misc.removeDoublesFromArray(b,Vector.compareByXThenY)}};function Skyum(){}Skyum.initTriangleArray=function(a){Skyum.triangles=[];for(var b=0;b<a.length;b++){var c=new Triangle(a[(b+a.length-1)%a.length],a[b],a[(b+1)%a.length]);Skyum.triangles.push(c)}};
Skyum.addNewTrianglesWithNeighboursOfPoint=function(a){var b=Skyum.remainingPoints.indexOf(a);a=(b+Skyum.remainingPoints.length-1)%Skyum.remainingPoints.length;var c=(b+1)%Skyum.remainingPoints.length,d=(b+2)%Skyum.remainingPoints.length,b=new Triangle(Skyum.remainingPoints[(a+Skyum.remainingPoints.length-1)%Skyum.remainingPoints.length],Skyum.remainingPoints[a],Skyum.remainingPoints[c]);a=new Triangle(Skyum.remainingPoints[a],Skyum.remainingPoints[c],Skyum.remainingPoints[d]);Skyum.triangles.push(b);
Skyum.triangles.push(a)};Skyum.calcVP=function(a,b){var c=LineSegment.createFromPoints(a,b),d=c.getCenter(),c=c.direction.rotate(Math.PI/2);return d.add(c.normalize().multiplyScalar(Misc.INFINITY))};
Skyum.initGlobals=function(a){Skyum.initTriangleArray(a);Skyum.remainingPoints=[].concat(a);Skyum.delaunayPoints=a;Skyum.voronoiPoints=[];Skyum.smallestCircle=null;Skyum.voronoiEdgeList=new EdgeList;Skyum.voronoiDiagram=[];Skyum.delaunayTriangulation=[];Skyum.voronoiNeighbours=[];for(var b=0;b<a.length;b++){var c=Skyum.calcVP(a[b],a[(b+1)%a.length]);Skyum.voronoiPoints.push(c)}};
Skyum.unifiedSkyum=function(a){var b;Skyum.initGlobals(a);if(2<a.length){do Skyum.triangles.sort(function(a,b){return-1*Triangle.compareByRadiusThenAngle(a,b)}),b=Skyum.triangles[0],Skyum.handleTriangle(b),Skyum.triangles=Skyum.triangles.filter(function(a){return!a.isCorner(b.p2)}),Skyum.addNewTrianglesWithNeighboursOfPoint(b.p2),a=Skyum.remainingPoints.indexOf(b.p2),Skyum.remainingPoints.splice(a,1);while(2<Skyum.remainingPoints.length);Skyum.handleRemainingLine()}else 2===a.length?Skyum.handleRemainingLine():
1===a.length&&(Skyum.smallestCircle=new Circle(a[0],0));Skyum.voronoiDiagram=Skyum.voronoiEdgeList.getLineSegments();Skyum.delaunayTriangulation=VoronoiDelaunay.computeDelaunay(Skyum.voronoiEdgeList).getLineSegments();Skyum.voronoiNeighbours=VoronoiDelaunay.computeVoronoiNeighbours(Skyum.voronoiEdgeList)};
Skyum.handleTriangle=function(a){null===Skyum.smallestCircle&&1!==Misc.compareWithTolerance(a.getMiddleAngle(),Math.PI/2)&&(Skyum.smallestCircle=a.getCircumcircle());var b=a.p2,c=a.p1,d=a.p3,f=a.getCircumcircle().center;a=Skyum.delaunayPoints.indexOf(b);a=Skyum.voronoiPoints[a];var e=Skyum.delaunayPoints.indexOf(c),g=Skyum.voronoiPoints[e];Skyum.voronoiPoints[e]=f;var e=Skyum.voronoiEdgeList.getNewHalfEdgePair(),h=Skyum.voronoiEdgeList.getNewHalfEdgePair(),k=Skyum.voronoiEdgeList.getNewVertex();k.coordinates=
f;k.incidentEdge=e.twin;var f=Skyum.voronoiEdgeList.getFace(b),l=Skyum.voronoiEdgeList.getFace(c),m=Skyum.voronoiEdgeList.getFace(d),n=Skyum.voronoiEdgeList.getVertex(a),p=Skyum.voronoiEdgeList.getVertex(g);null===f&&(f=Skyum.voronoiEdgeList.getNewFace(),f.vector=b,f.outerComponent=e);null===l&&(l=Skyum.voronoiEdgeList.getNewFace(),l.vector=c,l.outerComponent=h);null===m&&(m=Skyum.voronoiEdgeList.getNewFace(),m.vector=d,m.outerComponent=e.twin);null===n?(n=Skyum.voronoiEdgeList.getNewVertex(),n.coordinates=
a,n.incidentEdge=e):(f.outerComponent.getEnd().twin.origin===n&&f.outerComponent.getEnd().setNext(e),m.outerComponent.getStart().origin===n&&m.outerComponent.getStart().setPrev(e.twin));null===p?(p=Skyum.voronoiEdgeList.getNewVertex(),p.coordinates=g,p.incidentEdge=h):(f.outerComponent.getStart().origin===p&&f.outerComponent.getStart().setPrev(h.twin),l.outerComponent.getEnd().twin.origin===p&&l.outerComponent.getEnd().setNext(h));e.setNext(h.twin);e.origin=n;e.incidentFace=f;e.twin.origin=k;e.twin.incidentFace=
m;h.origin=p;h.incidentFace=l;h.twin.origin=k;h.twin.incidentFace=f};
Skyum.handleRemainingLine=function(){var a=Skyum.remainingPoints[0],b=Skyum.remainingPoints[1],c=Skyum.delaunayPoints.indexOf(a),d=Skyum.delaunayPoints.indexOf(b),c=Skyum.voronoiPoints[c],d=Skyum.voronoiPoints[d],f=LineSegment.createFromPoints(a,b);null===Skyum.smallestCircle&&(Skyum.smallestCircle=new Circle(f.getCenter(),f.getLength()/2));var f=Skyum.voronoiEdgeList.getFace(a),e=Skyum.voronoiEdgeList.getFace(b),g=Skyum.voronoiEdgeList.getVertex(c),h=Skyum.voronoiEdgeList.getVertex(d),k=Skyum.voronoiEdgeList.getNewHalfEdgePair();
null===f&&(f=Skyum.voronoiEdgeList.getNewFace(),f.vector=a,f.outerComponent=k.twin);null===e&&(e=Skyum.voronoiEdgeList.getNewFace(),e.vector=b,e.outerComponent=k);null===g?(g=Skyum.voronoiEdgeList.getNewVertex(),g.coordinates=c,g.incidentEdge=k.twin):(f.outerComponent.getEnd().twin.origin===g&&k.twin.setPrev(f.outerComponent.getEnd()),e.outerComponent.getStart().origin===g&&k.setNext(e.outerComponent.getStart()));null===h?(h=Skyum.voronoiEdgeList.getNewVertex(),h.coordinates=d,h.incidentEdge=k):(f.outerComponent.getStart().origin===
h&&k.twin.setNext(f.outerComponent.getStart()),e.outerComponent.getEnd().twin.origin===h&&k.setPrev(e.outerComponent.getEnd()));k.origin=h;k.incidentFace=e;k.twin.origin=g;k.twin.incidentFace=f};function TreeNode(a){this.rightChild=this.leftChild=this.parent=null;this.content=a}
TreeNode.prototype={isLeaf:function(){return null===this.leftChild&&null===this.rightChild},isRoot:function(){return null===this.parent},isLeftChild:function(){return this.isRoot()?!1:this===this.parent.leftChild},isRightChild:function(){return this.isRoot()?!1:this===this.parent.rightChild},isInLeftSubtree:function(a){var b=!1;this.leftChild.inorderDo(function(c){a===c&&(b=!0)});return b},isInRightSubtree:function(a){var b=!1;this.rightChild.inorderDo(function(c){a===c&&(b=!0)});return b},setLeftChild:function(a){this.leftChild=
a;a.parent=this},setRightChild:function(a){this.rightChild=a;a.parent=this},getLeftSibling:function(){if(this.isRoot())return null;if(this.isLeaf()){if(this.isRightChild())return this.parent.leftChild.getRightmostChild();var a=this.getLeftSiblingParent();return null!==a?a.getRightmostChild():null}return null},getRightSibling:function(){if(this.isRoot())return null;if(this.isLeaf()){if(this.isLeftChild())return this.parent.rightChild.getLeftmostChild();var a=this.getRightSiblingParent();return null!==
a?a.getLeftmostChild():null}return null},getLeftSiblingParent:function(){return this.isRoot()?null:this.isRightChild()?this.parent.leftChild:this.parent.getLeftSiblingParent()},getRightSiblingParent:function(){return this.isRoot()?null:this.isLeftChild()?this.parent.rightChild:this.parent.getRightSiblingParent()},getLeftmostChild:function(){return this.isLeaf()?this:this.leftChild.getLeftmostChild()},getRightmostChild:function(){return this.isLeaf()?this:this.rightChild.getRightmostChild()},getAncestor:function(a){return a(this)?
this:null!==this.parent?this.parent.getAncestor(a):null},getLeafs:function(){var a=[];null!==this.leftChild&&(a=a.concat(this.leftChild.getLeafs()));this.isLeaf()&&a.push(this);null!==this.rightChild&&(a=a.concat(this.rightChild.getLeafs()));return a},toString:function(){return this.content.toString()},inorderString:function(){var a="";null!==this.leftChild&&(a+=this.leftChild.inorderString());a+=this.toString();null!==this.rightChild&&(a+=this.rightChild.inorderString());return a},inorderList:function(){var a=
[];null!==this.leftChild&&(a=a.concat(this.leftChild.inorderList()));a.push(this);null!==this.rightChild&&(a=a.concat(this.rightChild.inorderList()));return a},inorderDo:function(a){null!==this.leftChild&&this.leftChild.inorderDo(a);a(this);null!==this.rightChild&&this.rightChild.inorderDo(a)}};function Tree(){this.root=null}
Tree.prototype={constructor:Tree,isEmpty:function(){return null===this.root},replaceNode:function(a,b){a.isRoot()?this.root=b:a.isLeftChild()?a.parent.setLeftChild(b):a.isRightChild()&&a.parent.setRightChild(b)},toString:function(){return this.root.inorderString()},inorderList:function(){return this.root.inorderList()},inorderDo:function(a){null!==this.root&&this.root.inorderDo(a)},getCommonAncestor:function(a,b){for(var c=a.parent;null!==c;){for(var d=b.parent;null!==d;){if(d===c)return c;d=d.parent}c=
c.parent}return null}};function Triangle(a,b,c){this.p1=a;this.p2=b;this.p3=c;this.angle=this.circumcircle=null}
Triangle.prototype={calcCircumcircle:function(){var a,b;b=Vector.calcDet(this.p1,this.p2,this.p3);if(0!==Misc.compareWithTolerance(b,0)){a=(Math.pow(this.p1.x,2)+Math.pow(this.p1.y,2))*(this.p2.y-this.p3.y)+(Math.pow(this.p2.x,2)+Math.pow(this.p2.y,2))*(this.p3.y-this.p1.y)+(Math.pow(this.p3.x,2)+Math.pow(this.p3.y,2))*(this.p1.y-this.p2.y);var c=(Math.pow(this.p1.x,2)+Math.pow(this.p1.y,2))*(this.p3.x-this.p2.x)+(Math.pow(this.p2.x,2)+Math.pow(this.p2.y,2))*(this.p1.x-this.p3.x)+(Math.pow(this.p3.x,
2)+Math.pow(this.p3.y,2))*(this.p2.x-this.p1.x),d=this.p1.y*(this.p3.x-this.p2.x)+this.p2.y*(this.p1.x-this.p3.x)+this.p3.y*(this.p2.x-this.p1.x);a=new Vector(0.5*a/d,0.5*c/d);b=Vector.calcDist(this.p1,this.p2)*Vector.calcDist(this.p2,this.p3)*Vector.calcDist(this.p3,this.p1)/(2*Math.abs(b))}else b=LineSegment.createFromPoints(this.p1,this.p2),a=LineSegment.createFromPoints(this.p1,this.p3),c=LineSegment.createFromPoints(this.p2,this.p3),b=[b,a,c],b.sort(function(a,b){return Misc.compare(a.getLength(),
b.getLength())}),a=b[2].getCenter(),b=b[2].getLength()/2;return new Circle(a,b)},getCircumcircle:function(){null===this.circumcircle&&(this.circumcircle=this.calcCircumcircle());return this.circumcircle},getMiddleAngle:function(){if(null===this.angle){var a=Vector.calcDistSquare(this.p1,this.p2)+Vector.calcDistSquare(this.p2,this.p3)-Vector.calcDistSquare(this.p1,this.p3),b=2*Vector.calcDist(this.p1,this.p2)*Vector.calcDist(this.p2,this.p3);0===Misc.compareWithTolerance(b,0)?this.angle=Math.PI:this.angle=
Math.acos(a/b)}return this.angle},isCorner:function(a){return this.p1.equals(a)||this.p2.equals(a)||this.p3.equals(a)}};Triangle.compareByRadiusThenAngle=function(a,b){var c=Misc.compareWithTolerance(a.getCircumcircle().radius,b.getCircumcircle().radius);return 0!==c?c:Misc.compareWithTolerance(a.getMiddleAngle(),b.getMiddleAngle())};function Vector(a,b){this.x=a;this.y=b}
Vector.prototype={constructor:Vector,rotate:function(a){var b=this.x*Math.cos(a)-this.y*Math.sin(a);a=this.y*Math.cos(a)+this.x*Math.sin(a);return new Vector(b,a)},switchCoordinates:function(){return new Vector(this.y,this.x)},mirrorY:function(){return new Vector(this.x,-1*this.y)},toString:function(){return""+this.x+","+this.y+""},multiplyScalar:function(a){return new Vector(a*this.x,a*this.y)},multiplyVector:function(a){return a.x*this.x+a.y*this.y},sub:function(a){return new Vector(this.x-a.x,
this.y-a.y)},add:function(a){return new Vector(this.x+a.x,this.y+a.y)},abs:function(){return Math.sqrt(this.x*this.x+this.y*this.y)},abssquare:function(){return this.x*this.x+this.y*this.y},normalize:function(){return this.multiplyScalar(1/this.abs())},equals:function(a){return 0===Vector.compareByXThenY(this,a)}};Vector.compareByX=function(a,b){return Misc.compareWithTolerance(a.x,b.x)};Vector.compareByY=function(a,b){return Misc.compareWithTolerance(a.y,b.y)};
Vector.compareByXThenY=function(a,b){var c=Vector.compareByX(a,b);return 0===c?Vector.compareByY(a,b):c};Vector.compareByYThenX=function(a,b){var c=Vector.compareByY(a,b);return 0===c?Vector.compareByX(a,b):c};Vector.calcDist=function(a,b){return a.sub(b).abs()};Vector.calcDistSquare=function(a,b){return a.sub(b).abssquare()};Vector.calcDet=function(a,b,c){return b.x*c.y+a.x*b.y+a.y*c.x-b.y*c.x-a.x*c.y-a.y*b.x};function VoronoiDelaunay(){}VoronoiDelaunay.computeDelaunay=function(a){var b=new EdgeList;a.faces.forEach(function(a){var d=a=a.outerComponent.getStart(),f=b.getVertex(d.incidentFace.vector);null===f&&(f=b.getNewVertex(),f.coordinates=d.incidentFace.vector);do{var e=d.twin.incidentFace.vector;if(null===b.getHalfEdge(f.coordinates,e)){var g=b.getVertex(e);null===g&&(g=b.getNewVertex(),g.coordinates=e);e=b.getNewHalfEdgePair();e.origin=f;e.twin.origin=g}d=d.next}while(null!==d&&d!==a)});return b};
VoronoiDelaunay.computeVoronoiNeighbours=function(a){var b=[];a.faces.forEach(function(a){var d=a=a.outerComponent.getStart(),f=d.incidentFace.vector;do{var e=d.twin.incidentFace.vector,g=LineSegment.createFromPoints(d.origin.coordinates,d.twin.origin.coordinates),e=LineSegment.createFromPoints(f,e),h=new VoronoiNeighbours(e,g);-1===Misc.getIndexInArrayWithPredicate(b,function(a){return a.equals(h)})&&b.push(h);d=d.next}while(null!==d&&d!==a)});return b};function VoronoiNeighbours(a,b){this.delaunayEdge=a;this.commonBorder=b}
VoronoiNeighbours.prototype={constructor:VoronoiNeighbours,getMinDist:function(){var a=this.commonBorder.origin,b=this.delaunayEdge.origin,c=this.commonBorder.pointProjection(b);if(null!==c)return c.sub(b).abs();c=this.commonBorder.getEndpoint();a=a.sub(b).abs();b=c.sub(b).abs();return Math.min(a,b)},getMaxDist:function(){var a=this.commonBorder.origin,b=this.commonBorder.getEndpoint(),c=this.delaunayEdge.origin,a=a.sub(c).abs(),b=b.sub(c).abs();return Math.max(a,b)},equals:function(a){return this.delaunayEdge.equals(a.delaunayEdge)&&
this.commonBorder.equals(a.commonBorder)}};
