package de.eseidinger.alpha_shapes_web;

import java.util.Set;
import javax.ws.rs.ApplicationPath;
import org.glassfish.jersey.media.multipart.MultiPartFeature;
import org.glassfish.jersey.server.ResourceConfig;

/**
 *
 * @author Emanuel Seidinger
 */
@ApplicationPath("resources")
public class AlphaShapesServerConfig extends ResourceConfig {
    
    public AlphaShapesServerConfig() {
        packages("de.eseidinger.alpha_shapes_web").register(MultiPartFeature.class);
    }

    /**
     * Workaround to prevent NetBeans from overriding final getClasses method.
     * 
     * @param foo 
     */
    private void getClasses(String foo) {
        
    }

    /**
     * Do not modify addRestResourceClasses() method.
     * It is automatically re-generated by NetBeans REST support to populate
     * given list with all resources defined in the project.
     */
    private void addRestResourceClasses(Set<Class<?>> resources) {
        resources.add(de.eseidinger.alpha_shapes_web.AlphaShapeSvgService.class);
        resources.add(de.eseidinger.alpha_shapes_web.PointsJsonService.class);
    }

}
